sonar.projectKey=stephenlclarke_containerization
sonar.organization=stephenlclarke
sonar.projectName=Containerization
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.sources=Sources,vminitd/Sources
sonar.tests=Tests
sonar.exclusions=**/.build/**,**/*.pb.swift,**/*.grpc.swift
sonar.test.inclusions=Tests/**/*.swift
