# Manual workflow for releasing docs ad-hoc. Workflow can only be run for main or release branches. 
# Workflow does NOT publish a release of containerization.
name: Deploy application website

permissions:
  contents: read

on: 
  workflow_dispatch:

jobs: 
  checkBranch:
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') || startsWith(github.ref, 'refs/heads/release')
    steps:
      - name: Branch validation
        env:
          REF_NAME: ${{ github.ref_name }}
        run: echo "Branch ${REF_NAME} is allowed"

  buildSite:
    name: Build application website
    needs: checkBranch
    uses: ./.github/workflows/documentation-build.yml
    secrets: inherit
    permissions:
      contents: read
      pages: write

  deployDocs:
    if: github.repository == 'apple/containerization'
    runs-on: ubuntu-24.04
    needs: [checkBranch, buildSite]
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e  # v4
